name: Docker CI

on:
  push:
    branches: [ "master" ]
env:
  # AWS & Elastic Bean Stalk
  AWS_REGION: ap-northeast-2
  EB_ENVIRONMENT_NAME: Snpservice-env-1
  EB_APPLICATION_NAME: snp-service

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v3
      
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t snp-app .
          docker tag snp-app jackghl/snp-service:front
          docker push jackghl/snp-service:front
       
      
  
  deploy:
     runs-on: ubuntu-latest
     name: Deploy(Production)
     needs: build
     steps:
      - uses: actions/checkout@v3
        
      
      - name: Generate docker-compose.yml
        run: echo "${{ secrets.DOCKER_COMPOSE }}" > docker-compose.yml
      
      # Beanstalk
      - name: Beanstalk Deploy
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESSKEY }}
          application_name: ${{ env.EB_APPLICATION_NAME }}
          environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
          version_label: "react-front-v${{ github.run_number }}"
          region: ${{ env.AWS_REGION }}
          deployment_package: docker-compose.yml
